### ISSUE TITLE
Sensitivity

### ISSUE THREAD

**Issue by NyrZ** [UnRealDinnerbone/SimpleZoom-Fabric#3]
The Zoom sensitivity does not match my sensitivity

**Comment by UnRealDinnerbone** [comment]
When your zoomed in your sensitivity does not change? It might just be the effect of zooming, as moving when zoom it still moves the same amount as not zoomed

**Comment by UnRealDinnerbone** [comment]
I can add a config that makes it so you move slower when zoomed

**Comment by NyrZ** [comment]
When I zoomin with Optifine moving like 5cm with my mouse moves as much as if I wasn't zoomed in but with your mod moving 5cm while zoomed is like moving 20cm or more not zoomed in

**Comment by NyrZ** [comment]
Even a setting to adjust the sensitivity when zoomed could be great

**Comment by UnRealDinnerbone** [comment]
Yha optifne changes your sensitivity when zoomed

**Comment by UnRealDinnerbone** [comment]
Added Config And Uploaded https://minecraft.curseforge.com/projects/simplezoom-fabric/files/2710377
